site_name: Stock Market Documentation
site_description: Documentation for the Stock Market project
site_author: Sujay Shrivastava

nav:
  - Home: README.md
  - Script Information: script_information.md
  - Available Strategies: available_strategies.md
  - Strategy Instructions: strategy_instructions.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    # - navigation.tabs
    - content.code.annotate
    - toggle.color-mode
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.tabs.sticky
    - navigation.tabs.animated

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo



markdown_extensions:
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
